## Import Required Libraries

In [1]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.action_chains import ActionChains
from webdriver_manager.chrome import ChromeDriverManager
from time import sleep

## Setup the Chrome Browser

In [2]:
chrome_options = Options()
chrome_options.add_experimental_option("detach", True)

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()),options=chrome_options)
driver.get('https://www.linkedin.com/jobs/collections/recommended/?currentJobId=3915398562&eBP=CwEAAAGPQr10misvYwRMkmBau7ZcUzLVpNuxjjoBHUjQUeeyS0JzL9Y4t2LCgqqXLBiuBBcczg5FyFDt-6PpFbxV6McM0DV-H0dgGzOw6aDAtnViMA6uJ4XQR79P05TPmKNgcW1-8QdFIsnkOenF-KyzoWSjo53qHy8-VZ--LHG6MKtrkz3BqxseTnrXpUebe-uAde3c_vGiYpw7uwpxaKOYuBiw84XPveLAzQrw9lgmD_ltpaVqSoWDLn3Yjt50NlHgfmVVtbcsre98yPjxI4pyNe40k71CrAZkv9CGFatJTqeH_NV_3nh6WoUmhezN2Aumu8sNXdy_Pqlbw2wo3t9tYsAUBVcEwKiHF9ZZDg0YGFMiJjbWo1zfGTELCQOEc8RB8OMvAbgK_UK-9NXEqEv1Mmp_jgz9VmUu8GVCRAzO-Ph-NY_S2gagS4p14XsF1U7RBMM&refId=IqzVl2kv%2BJfWL57XUP90IA%3D%3D&trackingId=%2BBdHRDj2rjlgFiNOmTSyLg%3D%3D')

sleep(4)
driver.maximize_window()

## Login into the LinkedIn Account

In [3]:
user = driver.find_element(By.XPATH,'//input[@id="username"]')
# Put here username for login
user.send_keys("USER NAME")

password = driver.find_element(By.XPATH,'//input[@id="password"]')
# Put here password for login
password.send_keys("PASSWORD")

submit = driver.find_element(By.XPATH,"//button[@class='btn__primary--large from__button--floating']")
submit.click()
sleep(5)

## Search the job title and location

In [4]:
search_bar = driver.find_element(By.XPATH,'//input[@autocomplete="organization-title"]')
search_bar.send_keys("Web Scraping")

location = driver.find_element(By.XPATH,'//input[@autocomplete="address-level2"]')
location.send_keys("India")

sub = driver.find_element(By.XPATH,'//*[@id="global-nav-search"]/div/div[2]/button[1]')
sub.click()
sleep(3)

## Scroll the job webpage

In [10]:
for a in range(1,10):
    scrolls = driver.find_elements(By.XPATH,'//div[@data-view-name="job-card"]')
    for sc in scrolls:
        driver.execute_script("arguments[0].scrollIntoView();",sc)
        #sleep(5)

## Scrape the data of jobs

In [11]:
jobs = []
companies = []
locat = []
for i in range(1,26):
    link = driver.find_element(By.XPATH,"/html/body/div[5]/div[3]/div[4]/div/div/main/div/div[2]/div[1]/div/ul/li[{}]/div/div/div[1]/div[1]/div[2]/div[1]/a".format(str(i)))
    link.click()
    Job = driver.find_element(By.XPATH,"//h1/a")
    jobs.append(Job.text)
    company = driver.find_element(By.XPATH,"(//a[@class='app-aware-link '])[2]")
    companies.append(company.text)
    loc = driver.find_element(By.XPATH,"//div[@class='job-details-jobs-unified-top-card__primary-description-without-tagline mb2']")
    locat.append(loc.text)
    #sleep(5)

## Create the dataframes of jobs data

In [12]:
data = pd.DataFrame()
data["Job Title"] = jobs
data["Company Name"] = companies
data["Job Location"] = locat

data

,Job Title,Company Name,Job Location
0,Python Tech lead,Tata Consultancy Services,"Tata Consultancy Services · Mumbai, Maharashtr..."
1,Python ETL developer,HTC Global Services,"HTC Global Services · Chennai, Tamil Nadu, Ind..."
2,Data Engineer (Python),TELUS International India,"TELUS International India · Noida, Uttar Prade..."
3,Datastage Developer,Tata Consultancy Services,"Tata Consultancy Services · Bengaluru, Karnata..."
4,AI Specialist- LLMs and RAG,ScaleGenAI,ScaleGenAI · India · 5 days ago · Over 100 app...
5,Lead Software Engineer (Web Scraping),Infiniti Research Ltd.,"Infiniti Research Ltd. · Bangalore Urban, Karn..."
6,Search Engine Optimization Executive,ASEUM INFOTECH PVT LTD,"ASEUM INFOTECH PVT LTD · Ahmedabad, Gujarat, I..."
7,Splunk Developer/Admin,Tata Consultancy Services,"Tata Consultancy Services · Pune, Maharashtra,..."
8,Web Specialist,Foresiet,Foresiet · India · 1 week ago · Over 100 appli...
9,IICS Developer,Tata Consultancy Services,"Tata Consultancy Services · Mumbai, Maharashtr..."
10,Web Scraping Engineer,Stealth AI Startup,Stealth AI Startup · India · 2 weeks ago · Ove...
11,OAC Report Developer,Heuristics Informatics Pvt. Ltd.,"Heuristics Informatics Pvt. Ltd. · Gurugram, H..."
12,Senior Web Scraper - Remote,Adit,Adit · India · 1 week ago · 94 applicants
13,Web Scraper – Fresher,Sustainability Economics,"Sustainability Economics · Bengaluru, Karnatak..."
14,Python-Web Scraping,Infiniti Research Ltd.,"Infiniti Research Ltd. · Bengaluru, Karnataka,..."
15,Interesting Job Opportunity: Python Intern - D...,Mobifly,"Mobifly · Delhi Cantonment, Delhi, India · 18..."
16,Search Engine Optimization Specialist,Throttll,"Throttll · Jaipur, Rajasthan, India · 1 week a..."
17,Lead Software Engineer (Python + Web Scraping),Infiniti Research Ltd.,"Infiniti Research Ltd. · Bengaluru, Karnataka,..."
18,Python Automation,KPIT,KPIT · Greater Bengaluru Area · 2 weeks ago · ...
19,Solumina Developer (Contract),Smart IT Frame LLC,"Smart IT Frame LLC · Chennai, Tamil Nadu, Indi..."
20,Internship - Web Development,Doutya Technologies,Doutya Technologies · India · 10 minutes ago ·...
21,Python Developer,Truelancer.com,"Truelancer.com · Noida, Uttar Pradesh, India ·..."
22,Technical Lead,ToneOpFit,"ToneOpFit · Bhopal, Madhya Pradesh, India · 3 ..."
23,Growth Hacker,Klizo Solutions Pvt Ltd,"Klizo Solutions Pvt Ltd · Kolkata, West Bengal..."
24,Django/ Python Trainee,AccuKnox,AccuKnox · India · 4 weeks ago · Over 100 appl...

## Data Exporting in the CSV format

In [13]:
data.to_csv("Jobs data.csv")

In [14]:
driver.quit()